server:
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobtrackr-db

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://api.jobtrackrpro.com/login/oauth2/code/google
          linkedin:
            redirect-uri: https://jobtrackrpro.com/login/oauth2/code/linkedin
          github:
            redirect-uri: https://api.jobtrackrpro.com/login/oauth2/code/github
          facebook:
            redirect-uri: https://api.jobtrackrpro.com/login/oauth2/code/facebook

aws:
  cloudfront:
    privateKeyPath: /keys/jobtrackr-cf_private.pem

app:
  frontend:
    url: https://jobtrackrpro.com

brightdata:
  webhook-callback-url: https://api.jobtrackrpro.com/webhooks/brightdata

stripe:
  secret-key: ${STRIPE_API.key}
  checkout:
    success-url: https://app.jobtrackrpro.com/account?checkout=success
    cancel-url: https://app.jobtrackrpro.com/account?checkout=cancelled
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}


